repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0  # Use a specific version or 'stable' for the latest stable version
    hooks:
      - id: black
        language_version: python3.11  # Specify the Python version 'black' should run with
